#pragma once

#include "snuk/defines.h"

typedef enum SnukErrorCode {
    SNUK_ERROR_NONE = 0,
    SNUK_ERROR_SHOULD_NOT_REACH_HERE,
    SNUK_ERROR_SOMETHING_WENT_WRONG,
    SNUK_ERROR_CONTROL_FLOW,
    SNUK_ERROR_EXISTS,
    SNUK_ERROR_NON_TYPE,
    SNUK_ERROR_EXPECT_ASSIGN,
    SNUK_ERROR_BUILTIN_INVALID_VALUE,
    SNUK_ERROR_MEMBER_INITIALIZE,
    SNUK_ERROR_SELF_CREATION,
    SNUK_ERROR_PARAM_CREATION,
    SNUK_ERROR_NON_FN,
    SNUK_ERROR_PARAM_COUNT,
    SNUK_ERROR_NO_PARAM,
    SNUK_ERROR_PARAM,
    SNUK_ERROR_PARAM_REQUIRED,
    SNUK_ERROR_SELF,
    SNUK_ERROR_SET_ENV_FAIL,
    SNUK_ERROR_MEMBER,
    SNUK_ERROR_INTERFACE,

    SNUK_ERROR_MAX,
} SnukErrorCode;

SNUK_API const char *snuk_error_code_get_text(SnukErrorCode code);
